[package]
name = "timah"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
home = "0.5.5"
ncurses = {version = "5.101.0", features = ["wide"]}
shellexpand = "3.1.0"
